name: Jekyll com Docker

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build Jekyll com Docker jekyll/builder
        uses: docker://jekyll/builder:latest
        with:
          args: >
            /bin/bash -c "
            chmod -R 777 /github/workspace &&
            jekyll build --future
            "

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
